#include<iostream.h>
#include<conio.h>
#include<stdlib.h>
#include <math.h>
#include "CODE01.H"
#include "CODE02.H"
#include "CODE03.H"
#include "CODE04.H"
#include "CODE05.H"
#include "CODE06.H"
#include "CODE07.H"
#include "CODE08.H"
#include "CODE09.H"
#include "CODE10.H"
#include "CODE11.H"
#include "CODE12.H"
#include "CODE13.H"
#include "CODE14.H"
#include "CODE15.H"
#include "CODE16.H"
#include "CODE17.H"
#include "CODE18.H"
